### ISSUE TITLE
Turn wiki into GH page

### ISSUE THREAD

**Issue by Eremiell** [rawiriblundell/wiki.bash-hackers.org#12]
Not sure how much work is there still to fill the full wiki and turn it into md, but feels like turning it into a GH page once all the work is done could give us back the seamless interface we used to have on the original wiki.

**Comment by flokoe** [comment]
I just crawled the entire wiki, converted and published them via GitHub Pages:

https://flokoe.github.io/bash-hackers-wiki/
https://github.com/flokoe/bash-hackers-wiki

There is still some work to do as not all pages are formatted correctly. So for everyone who is interested in helping out, feel free to open PRs. Any help is welcome.

**Comment by rawiriblundell** [comment]
Hi guys,
thanks for the assist.  I've updated README.md with the above links 👍 

Rawiri
