### ISSUE TITLE
Crawling the entire wiki to save the current source text files

### ISSUE THREAD

**Issue by flokoe** [rawiriblundell/wiki.bash-hackers.org#13]
Hi there,

DokuWiki allows viewing the original raw WikiText source files by appending `?do=export_raw` to any URL. As long as the original server is online, I could probably crawl the entire wiki and archive all the current versions of the original source files. I used this wiki as a reference occasionally, and it would be a great loss to lose all this information. If there is enough interest in this, I would be happy to help.

Best regards

**Comment by flokoe** [comment]
To preserve the information, I just crawled the entire wiki, converted and published them via GitHub Pages:

https://flokoe.github.io/bash-hackers-wiki/
https://github.com/flokoe/bash-hackers-wiki

There is still some work to do as not all pages are formatted correctly. So for everyone who is interested in helping out, feel free to open PRs. Any help is welcome.

**Comment by rawiriblundell** [comment]
Thanks for the heads up, as mentioned in the other issue I've added your links to README.md.

At a quick glance - and just for my curiosity - it doesn't look like `?do=export_raw` pages are available via the wayback machine, so definitely grabbing them off the original server is the way to go.  I've also already run httrack against the original server and have 3.5GB of raw data.  Probably none of which will be necessary, but still good to have that time-capsule just in case :)

Rawiri
