### ISSUE TITLE
check the reddit thread...

### ISSUE THREAD

**Issue by ScoobyDone** [rawiriblundell/wiki.bash-hackers.org#3]
just an fyi, don't know if you saw it but...

the server is still available via IP, the hostname is dead but the server is not.  you can hit the server directly, no need for archive.org...

**Comment by rawiriblundell** [comment]
Hi, thanks for that.  You might like to check README.md, specifically 029ca20 :)

I've run an HTTrack against it, as that was mentioned in the thread as well, and stopped it after several hours.  92k files which make up 3.4G of text data.

It's a pretty big haystack to trawl, but it helped me to fill in the obsolete.md gap last night.

Thanks again :)
