### ISSUE TITLE
`syntax/ccmd/conditional_expression` missing

### ISSUE THREAD

**Issue by gabe565** [rawiriblundell/wiki.bash-hackers.org#4]
Hey! I'm working on generating a site from this documentation (it's not quite ready yet, but you can see it at https://bash-hackers.gabe565.com) and during doc generation, it looks like some files reference [`syntax/ccmd/conditional_expression.md`](https://web.archive.org/web/20230306130835/https://wiki.bash-hackers.org/syntax/ccmd/conditional_expression) which doesn't exist in this repo:
```
WARNING  -  Documentation file 'README.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'commands/classictest.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'scripting/bashchanges.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'syntax/arith_expr.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'syntax/basicgrammar.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'syntax/pattern.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'syntax/quoting.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
WARNING  -  Documentation file 'syntax/ccmd/case.md' contains a link to 'syntax/ccmd/conditional_expression.md' which is not found in the documentation files.
```

(`README.md` is actually `start.md`. I renamed it so that it's the index page of the site)

There are a few other missing files, but their URLs make them look less important. I'll check the archive.org contents for these:
```
WARNING  -  Documentation file 'commands/builtin/declare.md' contains a link to 'commands/builtin/read.mdonly' which is not found in the documentation files.
WARNING  -  Documentation file 'commands/builtin/let.md' contains a link to 'commands/builtin/...' which is not found in the documentation files.
WARNING  -  Documentation file 'howto/mutex.md' contains a link to 'howto/sunny_delhi18@yahoo.com' which is not found in the documentation files.
```

Edit: None of those files exist in the archive, so they may have 404'd on the original site. The reference to `commands/builtin/...` seems to be a markdown parsing issue that I'll look into.

**Comment by gabe565** [comment]
Also, I made some other changes in my fork that will require changes to the generation script. I'll get around to updating that eventually.

1. I use [MkDocs](https://www.mkdocs.org/) and [MkDocs Material](https://squidfunk.github.io/mkdocs-material/) which unfortunately doesn't support absolute paths, so I had to replace all of those with relative paths
2. All markdown files had to be moved into a `docs` directory. This one should be simple enough to update in the script.
3. `start.md` is now `README.md`
4. I added front-matter to `README.md` so I could hide the left pane:
   ```yaml
   ---
   hide: [navigation]
   ---
   ```

**Comment by rawiriblundell** [comment]
Hi Gabe!
I've manually recovered and added the conditional_expression.md file, which should resolve the bulk of this.

On review, the read.mdonly link should probably be readonly.md - fixed.

The builtin/... link might have been part of a Discussion section that was on the original page.  I think I've removed this.

The @yahoo.com link appears to be legit - unchanged.

Commits inbound, see what you think :)

Rawiri

**Comment by gabe565** [comment]
Awesome! Thank you :) I'll pull your changes into my fork. Would you be opposed to me updating the script to do number 1 and 2 on my list above? That would make it easier for me to keep my fork in sync

**Comment by gabe565** [comment]
Looks great! The only warning left is that email which isn't a big deal, I just wanted to be sure no content was missing

**Comment by rawiriblundell** [comment]
> Awesome! Thank you :) I'll pull your changes into my fork. Would you be opposed to me updating the script to do number 1 and 2 on my list above? That would make it easier for me to keep my fork in sync

Hey, not opposed at all.  Looks like a reasonable and flexible move.  I'll close this issue off as we look to be done here, throw in a PR for the 1&2 changes :)
